### PR TITLE
Release 1.0.0 with localization, declare WP 5.7 compatibility

### PR DESCRIPTION
**Pull request by patrickrobrecht**
* Localize the plugin via Translate WordPress (see [support forum](https://wordpress.org/support/topic/german-l10n/))
* Add code style check and make code compatible with WP CS
* Release as 1.0.0 to add a statement on the public API (as done for (SPCL](https://github.com/pluginkollektiv/blacklist-updater/pull/20#issue-568595202) as well)
* Declare compatibility with WordPress 5.7

### CODE REVIEW

**Comment by Zodiac1978** [comment]
I am not able to give feedback to all of the changes (no knowledge about composer), the rest looks good to me!

Just a question (although the problem is not in the PR, it exists before, just saw it now):
If we add the sentence: "Next check for a new block list in" but the event is not scheduled and returns false it ends up with the sentence: "Next check for a new block list in never". Better than "Never" (capitalized), but still no real sentence, or not?

**Comment by stklcode** [comment]
Technically LGTM.

However, we do jump from 0.0.6 to 1.0.0 and already adjusted wording from black- to blocklist in various places. Isn't this the point in time where we might consider renaming the plugin itself to, let's say _Blocklist Updater_ ?

I've recently done the same for _Statify Blacklist_ (now _Statify Filter_) preserving the old slug, which didn't cause any trouble.

**Comment by patrickrobrecht** [comment]
> However, we do jump from 0.0.6 to 1.0.0 and already adjusted wording from black- to blocklist in various places. Isn't this the point in time where we might consider renaming the plugin itself to, let's say _Blocklist Updater_ ?

I totally agree here. As we use "block list" in the frontend already, I've updated the plugin name to _Block List Updater_ as rephrased all descriptions from blacklist to "block list" (2 words). Just the slug and class/method prefix stays "blacklist".

**Comment by splorp** [comment]
Will it cause any problems for this plugin once I finally get around to renaming my [Comment Blacklist for WordPress](https://github.com/splorp/wordpress-comment-blacklist)?

I’d like to take the direction you have and rename the project to _“Comment Block List for WordPress”_ … also changing the repo name from `wordpress-comment-blacklist` to `wordpress-comment-block-list`. It appears that GitHub will [automatically handle redirection](https://docs.github.com/en/github/administering-a-repository/renaming-a-repository) of the legacy slug to the new repo path, so that shouldn’t be an issue.

**Comment by patrickrobrecht** [comment]
@splorp Thanks for asking. The redirection should handle everything, otherwise we'll publish a bugfix release immediately. I've subscribed to https://github.com/splorp/wordpress-comment-blacklist/issues/27, so I'll get notified if you close the issue.

We'll keep the slug as WordPress.org does not allow to change plugin slugs.

**Comment by splorp** [comment]
Cool. Sounds good.

**Comment by stklcode** [comment]
LGTM.

We should though Update the GH action versions to keep it consistent across our plugins, i.e. `actions/checkout@v2` and `10up/action-wordpress-*@stable`

https://github.com/pluginkollektiv/blacklist-updater/blob/26f78e596a484271dff245926075d9c69a4cb48f/.github/workflows/wordpress-plugin-asset-update.yml#L11-L13

https://github.com/pluginkollektiv/blacklist-updater/blob/26f78e596a484271dff245926075d9c69a4cb48f/.github/workflows/wordpress-plugin-deploy.yml#L12-L14

**Review by stklcode — APPROVED** [review]

**Pull request merged**
